### ISSUE TITLE
Instructions of Final Capstone Project!

### ISSUE THREAD

**Issue by mukhammadrizooff** [mukhammadrizooff/JayPeakTours-backend#15]
# Hi There 👋 - Description of project.
### Information of project:
- #### [GitHub Project Board link](https://github.com/mukhammadrizooff/JayPeakVermont-backend/projects/1)
### Team members :
- #### @gabyse1 
- #### @sumairq 
- #### @mukhammadrizooff
- ## Kanban Screenshot:
![image](https://user-images.githubusercontent.com/63915024/174460144-ad7cdc97-1842-45d6-983c-6d90f0538903.png)

**Comment by MuriloRoque** [comment]
Hi @sumairq, @mukhammadrizooff, @gabyse1,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
